language: node_js
node_js: node
before_install:
- openssl aes-256-cbc -K $encrypted_8a3d438a572c_key -iv $encrypted_8a3d438a572c_iv
  -in .git-credentials.enc -out $HOME/.git-credentials -d
- git config --global credential.helper store
- git config --global user.email "travis@trajano.net"
- git config --global user.name  "Travis Service Account"
- git clone https://github.com/trajano/trajano-portfolio.git -b gh-pages --depth 1 dist
- git -C dist rm -rf .
after_success:
- git -C dist add .
- git -C dist commit -a -m "Travis build"
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git -C dist push origin gh-pages; fi
