sudo: false
language: node_js
node_js: node
cache:
  directories:
  - "$HOME/.sonar/cache"
  - node_modules
addons:
  apt:
    packages:
    - oracle-java8-set-default
  sonarqube:
    token:
      secure: eXtBZT9bMoAUHwVxP2g0zyN0S1AbnqzizgwyfQlMq19jpmcHwmhfscRxbG8+/b2ETVPCt70fFp3tputlq+BwyUCOCMstix1ErPRAyxYtoa9JkkRsCn1em1rE71RbVLWJDjL7HtYWl4NxBvR2yr/L/DsrhL/kzQUT/9p/Xr2hDaY8sJMAj7VUpDuJsLTaYUmIiuP7DOoJLx6NzHgHsC/divUNtRspj5slO7sVhtZkeZNq67NOgNZ3UO/2LYSDM+XUMpoK4W1mq2B8qMGss9X+PTqDdz2TcJJUGXKZnNf/5UhXdxrORYPsdbQhaHTN/kTVz5ND4a84I4ccb+/4KJxPV9HPUSrekI4eACsbuXyxFNkfEUvKuQRGoC2FCVu3Ro191JrEex8n5x/GMyoOxR8qAZGJl6Qqx5MSGGYGZWugG9j6O/tt2y/zB9rnXnZAw15ntg6orb5n2AdHWrivsZbc5UNBECpsEANg/hPKOg9O1EM5FpeqIX+WYm03TGg4cZisoOASZkq3G/2Hz6H0iqM2i6P3rRsdXe6VqOdC3hvtshMNUgdFQ0eSIQaY0Mz3Y63vOrwi3NizEtFckmLv/sX7B8aXG0rxaZg9oJvBT3VkEhHqPtbCdSmjAPzl8qiMiWjlFaWKKwg6/A5tzubCxFzP9SgFNA373TplKb+vH/eBRvg=
branches:
  only:
  - master
env:
  global:
  - secure: oT7xfu5SSZ7Nxcg1Lcp0zuay9IKZKbOzdu1Ug5/cljsDuWiGyBrvIEKjyA+j5F0PrT1oT9jXARYEXh55BF8RJFKhDdHz+uII+dhCuTo+8QVYL2GzkqL8yMEDhpoqQGyj+PSzXxkxm4/Jg5eyEPGVYsi2puOhOR/hzwaoagxwxZs9Fseqxa7LV4A9W9TEFP2/o+/oE2o+g8sgk1bNn4/3Rcqc9FTCP63aXzNfO7aV8gjxlWnO8lExhNr6XApDKrQAZ4fGBA68m+uWg+VSvQdLcZ6hlhSVn96ZLLNNVst38e4ehusqS2KlqUL7l+in1u1dNTgyhejpzaRCLTPZxQMMi9qwFr0uUl4jV4IFn5klQ7tkXnO9yTeE54IQIncdDxGoYuPAX3oTzVHiYHsQkP9jQupwAMPF7W6H7nBjspDVCakh2yR/+felX3ex/ls7UCR0c749swb7+/LEXiz3hu0r0vOyIv79JwvD6PHZEfOgVW6wYefndZEXtXEmd7K6UrO7os+lOPDjgw27HCdHLdnDmDSy3lHXLWm0SWipZ4KDlfnyDkxmRjRa0MTmfoCARiCNMbOtZZSCNFzRSXALcQygpticO7g+sPhkVwccVpZuujr+xAmQE9vYadGrd7Xh32fd7lLG6mPCQp62AqJdoKhUnsFMvBL2o2c2/bZqUqhem7I=
script:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
- sonar-scanner
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: "${SONAR_GITHUB_TOKEN}"
  on:
    branch: master
    node_js: node
