language: node_js
node_js: node
before_install:
- openssl aes-256-cbc -K $encrypted_8a3d438a572c_key -iv $encrypted_8a3d438a572c_iv
  -in .git-credentials.enc -out $HOME/.git-credentials -d
- git config --global credential.helper store
- git config --global user.email "travis@trajano.net"
- git config --global user.name  "Travis Service Account"
after_success:
- git -C dist add -A
- git -C dist commit -a -m "Travis build"
- git -C dist rebase origin/gh-pages
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then git -C dist push origin HEAD:gh-pages; fi
